### ISSUE TITLE
Антон Белый, 2539

### ISSUE THREAD

**Issue by AVBelyy** [itmoasm2015/Homework1#1]
2539/Belyy

**Comment by imihajlow** [comment]
```
Test failed: "%+10-0000d" -> expected "%+10-0000d", got "+123      "
```

**Comment by imihajlow** [comment]
```
Test failed: "%ll+u" -> expected "%+u", got "+123"
```

**Comment by AVBelyy** [comment]
OK, my bad – I didn't handle malformed sequences correctly. Fixed this and now am ready for re-test.

For the future reference – what is the best way to test our implementation on some input?
If, for some test, output of our hw_sprintf() matches output of sprintf(), it is enough to be considered valid response for the test?

**Comment by imihajlow** [comment]
Да, можно тестировать на совпадение результатов со sprintf. Единственная разница — в стандартной sprintf у беззнаковых чисел никогда не отображается знак, даже если есть флаг "+".

По коду: зачем используется магия с умножением на -858993459? Почему просто не поделить на 10?
Зачем вместо call используется push и jmp? Везде, где я нашел такую конструкцию, можно использовать call и Jcc с противоположным условием.
Замечание по именованию: константы xxx_STATE на самом деле означают не состояние, а флаги, было бы разумнее назвать их xxx_FLAG.

Результат 6/8 код и 5/7 комментарии (не объяснена магия с делением, _STATE вместо _FLAG и т.д.) плюс бонус 4 балла за сдачу первым.

**Comment by AVBelyy** [comment]
> По коду: зачем используется магия с умножением на -858993459? Почему просто не поделить на 10?

Потому что это не такая уж и магия (а вполне известный трюк, о котором нам рассказывали на курсе С++) и потому, что операция div выполняется гораздо медленнее. Одно из преимуществ ассемблера в том, что вместе реализации алгоритма "в лоб" я могу использовать какую-то такую магию.

> Зачем вместо call используется push и jmp? Везде, где я нашел такую конструкцию, можно использовать call и Jcc с противоположным условием.

Потому что conditional jump сделать проще, чем conditional call: для последнего надо создавать отдельную метку, в которую делать conditional jump, в которой делать обычный call. Это бы удлинило и усложнило для понимания и без того непростой код.

> Замечание по именованию: константы xxx_STATE на самом деле означают не состояние, а флаги, было бы разумнее назвать их xxx_FLAG.

_STATE означало принадлежность константы к переменной STATE, имя _FLAG уже было зарезервировано для флагов в синтаксисе управляющих блоков sprintf (например, FLAG_ZERO_STATE)

**Comment by imihajlow** [comment]
Хорошо :) Посмотрим, насколько ваша версия окажется быстрее тех, кто использует div.

**Comment by AVBelyy** [comment]
> 5/7 комментарии (не объяснена магия с делением, _STATE вместо _FLAG и т.д.) 

Объяснил выше и то, и другое. Прибавите баллы? :)
