### ISSUE TITLE
2539/Bisyarina

### ISSUE THREAD

**Issue by marianna-b** [itmoasm2015/Homework1#12]

**Comment by imihajlow** [comment]
```
make[1]: *** No rule to make target `test.cpp', needed by `test.o'.  Stop.
```

**Comment by marianna-b** [comment]
Fixed.

**Comment by imihajlow** [comment]
Не работает "%01000000d"

**Comment by marianna-b** [comment]
Fixed.

**Comment by imihajlow** [comment]
```
Test failed: "%+5u" -> expected 5 "  +51", got 5 "   51"
```

**Comment by marianna-b** [comment]
sprintf has the same output on this test as my code. Will fix it, but the compiler warns on the format string like this one.

**Comment by marianna-b** [comment]
Fixed.

**Comment by imihajlow** [comment]
В этом поведение нашей функции отличается от sprintf. См. второй пример из pdf с заданием.

**Comment by marianna-b** [comment]
Понятно, не заметила. Исправлено.

**Comment by imihajlow** [comment]
У вас в программе нет ни одной инструкции ret. Почему же она не вылетела? Программа слинковалась так, что после вашей функции идет сразу функция инициализации libc, куда сразу же и попадает управление, а там уже есть ret.

**Comment by marianna-b** [comment]
Поправила.

**Comment by imihajlow** [comment]
Код 5/8, комментарии 5/7.
