### ISSUE TITLE
Проверьте мои старания плез.

### ISSUE THREAD

**Issue by aga-ad** [itmoasm2015/Homework1#2]
2539/Aganov

**Comment by imihajlow** [comment]
Вы не сохраняете регистры, которые нужно сохранять согласно конвенции вызова.

http://en.wikipedia.org/wiki/X86_calling_conventions#cdecl

**Comment by aga-ad** [comment]
Исправил.

**Comment by imihajlow** [comment]
```
Test failed: "%0%d" -> expected "%0123", got "%d"
```

**Comment by imihajlow** [comment]
```
Test failed: "% l%d" -> expected "% l123", got "d"
```

**Comment by aga-ad** [comment]
Снова исправил.

**Comment by imihajlow** [comment]
Код 6/8, комментарии 3/7 (особенно удручает отсутствие констант для флагов). Бонус 2 балла за сдачу третьим.
