### ISSUE TITLE
Timofeev Kirill, 2536

### ISSUE THREAD

**Issue by KirillTim** [itmoasm2015/Homework1#22]
Забыл вчера вечером сделать issue, делаю сейчас. По коммитам видно. что я всё сдал до дедлайна. оцените, пожалуйста, работу, как сданную вовремя(фактически, но, к сожалению, не формально)

**Comment by imihajlow** [comment]
```
Test failed: "%+5d" -> expected "  +51", got "+  51"
```

Это второй пример из PDF с заданием (только d вместо u). Уж можно было хотя бы на тех тестах самостоятельно проверить?

**Comment by KirillTim** [comment]
Как так? Проверял на тестах из пдф и на своих. И всё было ок :( починю сейчас

**Comment by KirillTim** [comment]
починил все баги и почистил код

**Comment by imihajlow** [comment]
Код 5, комментарии 7.
