### ISSUE TITLE
nemchenko 2538

### ISSUE THREAD

**Issue by eugene536** [itmoasm2015/Homework1#23]
если нужны будут еще комментарии напишите, кажется, там более менее все ясно =)

**Comment by imihajlow** [comment]
```
Test failed: "%llu" -> expected 20 "18446744073709551615", got 1 "5"
```

**Comment by eugene536** [comment]
fixed

**Comment by imihajlow** [comment]
```
g++: error: ../Homework1/2538/nemchenko/libhw.a: No such file or directory
```

**Comment by eugene536** [comment]
ok, fixed

**Comment by imihajlow** [comment]
```
Test failed: "%lli" -> expected 10 "4294967296", got 0 ""
```

**Comment by eugene536** [comment]
fixed

**Comment by imihajlow** [comment]
segfault @ hw_sprintf.asm:419

**Comment by eugene536** [comment]
а можно тест, так сложно понять =(

**Comment by imihajlow** [comment]
```
"%01000000d"
```

**Comment by eugene536** [comment]
у меня все норм

**Comment by imihajlow** [comment]
Ну вам не повезло, значит, раз не падает. Segfault штука такая.

**Comment by eugene536** [comment]
а какое число передается ?

**Comment by imihajlow** [comment]
123

**Comment by eugene536** [comment]
неинициализированные переменные =(, пофиксил

**Comment by imihajlow** [comment]
Константы через equ не нужно класть в rodata, потому что они не существуют в памяти.
Еще на мой взгляд присвоение регистрам других имен через define вносит путаницу.

Код 6/8, комментарии 7/7.
