### ISSUE TITLE
Slyusarenko Maxim, 2538

### ISSUE THREAD

**Issue by MaximSlyusarenko** [itmoasm2015/Homework1#27]
2538/Slyusarenko

**Comment by imihajlow** [comment]
```
Test failed: "%wtf" -> expected "%wtf", got "%wtf6744073709551615"
```

**Comment by MaximSlyusarenko** [comment]
Fixed

**Comment by imihajlow** [comment]
Segfault на тесте `"%1000000d"`

**Comment by MaximSlyusarenko** [comment]
Правильно ли я понимаю, что этот тест означает, что минимальная ширина 4-байтового поля равна 1000000? Если это так, то хватает ли размера данного функции буффера, чтобы записать в него 1000000 символов?

**Comment by imihajlow** [comment]
Да, места в буфере там достаточно.

**Comment by MaximSlyusarenko** [comment]
Возможно, исправил. Сложно проверить, потому что у меня все работает

**Comment by imihajlow** [comment]
Теперь падает на `"%+10-0000d"`. У вас какая-то системная ошибка :)

**Comment by MaximSlyusarenko** [comment]
Исправил

**Comment by imihajlow** [comment]
Код 6, комметарии 7.
