### ISSUE TITLE
Замятин Евгений, 2539 (Zamyatin)

### ISSUE THREAD

**Issue by ezamyatin** [itmoasm2015/Homework1#3]

**Comment by imihajlow** [comment]
```
Test failed: "%ll %d" -> expected "%ll 123", got "% 123"
```

**Comment by ezamyatin** [comment]
sprintf работает также.
Вообще, не очень понятно, что с ll должно происходить при некорректной строке формата.

**Comment by imihajlow** [comment]
%ll — это неверное выражение, должно выводиться как есть. Оно не подходит под шаблон _%[флаги][ширина][размер]тип_

**Comment by ezamyatin** [comment]
Поправил.

**Comment by imihajlow** [comment]
Код 8/8, комментарии 4/7, бонус 3 балла за сдачу вторым.
