### ISSUE TITLE
Яковлева Дарья, 2539

### ISSUE THREAD

**Issue by DariaYakovleva** [itmoasm2015/Homework1#31]
2539/Yakovleva

**Comment by imihajlow** [comment]
```
Test failed: "%8u=%-8u" -> expected "    1234=1234    ", got "    1234=1234     "
```

**Comment by DariaYakovleva** [comment]
sorry:( fixed

**Comment by imihajlow** [comment]
```
Test failed: "%lld" -> expected "1152921504606846975", got "+1152921500311879681"
```

**Comment by DariaYakovleva** [comment]
исправила

**Comment by DariaYakovleva** [comment]
исправила

**Comment by imihajlow** [comment]
```
Test failed: "%-08d" -> expected "123     ", got "12300000"
```

Эх, Дарья, как невнимательно! Тестируйте лучше!

**Comment by DariaYakovleva** [comment]
ой, я лево и право перепутала.
исправила

**Comment by imihajlow** [comment]
`Test failed: "%+10-0000d" -> expected "%+10-0000d", got "+123      "`

**Comment by DariaYakovleva** [comment]
исправила

**Comment by imihajlow** [comment]
```
Test failed: "% l%d" -> expected "% l123", got "-18571438587781"
```

Эх, Дарья, ну напишите вы своих тестов-то побольше. Вас через четыре года на собеседовании в гугл спросят, как вы только что написанную функцию тестировать будете, а вы и не сможете ответить.

**Comment by DariaYakovleva** [comment]
написала тесты, протестировала, исправила, устала

**Comment by imihajlow** [comment]
```
Test failed: "%+5u" -> expected "  +51", got "   51"
```

Вы уж не переутомляйтесь, а то результат не очень.

**Comment by DariaYakovleva** [comment]
Sprintf считает, что здесь не нужно выводить +, я тестила с ним собственно
Вт, 19 мая 2015 г. в 10:38, Ivan Mikhaylov notifications@github.com:

**Comment by imihajlow** [comment]
Да, sprintf не выводит знак никогда, если число беззнаковое. Но в нашем задании такого условия нет, поэтому если формат содержит `+`, то знак выводится в любом случае, для беззнакового числа это плюс.

**Comment by DariaYakovleva** [comment]
исправила

**Comment by imihajlow** [comment]
```
Test failed: "%  " -> expected "%  ", got "%10+d"
```

**Comment by DariaYakovleva** [comment]
исправила

**Comment by imihajlow** [comment]
Код 5, комментарии 7.

И это, кажется, наибольшее количество багов.

**Comment by DariaYakovleva** [comment]
извините:(
