### ISSUE TITLE
Пересадин Илья, 2539

### ISSUE THREAD

**Issue by pva701** [itmoasm2015/Homework1#4]

**Comment by imihajlow** [comment]
Код 7/8, комментарии 5/7 (минус два балла за множество орфографических ошибок). Бонус 1 балл за сдачу четвертым.

**Comment by pva701** [comment]
А как насчет пунктуации, с ней все хорошо?
05.03.2015 12:59 пользователь "Ivan Mikhaylov" notifications@github.com
написал:
