### ISSUE TITLE
Кузнецов Николай, 2539

### ISSUE THREAD

**Issue by knah** [itmoasm2015/Homework1#5]
Получилось подозрительно много кода.
Комментариев я налил пожалуй слишком щедро, но уж лучше их будет много, чем мало. Неочевидный код хуже перекомментированого.

**Comment by imihajlow** [comment]
Не работают большие поля (например, "%1000000d").

**Comment by knah** [comment]
Исправлено, изначально думал что слишком большие поля - неразумно.

**Comment by imihajlow** [comment]
Код 8/8, комментарии 7/7.
