### ISSUE TITLE
Химуля Александр, 2537

### ISSUE THREAD

**Issue by viscount-sanchez** [itmoasm2015/Homework1#6]

**Comment by imihajlow** [comment]
make не делает libhw.a

**Comment by viscount-sanchez** [comment]
Исправлено.

**Comment by imihajlow** [comment]
Формат %i не поддерживается, а должен.

**Comment by viscount-sanchez** [comment]
Исправлено.

**Comment by imihajlow** [comment]
`Test failed: "%-%%d" -> expected 4 "%123", got 4 "%-%d"`

У нас % — это тоже тип, наряду с d, i и u, поэтому выражение %-% должно выводить просто %, игнорируя флаг (-).

**Comment by viscount-sanchez** [comment]
Прошу прощения за невнимательность, исправлено.

**Comment by imihajlow** [comment]
Код 5/8, комментарии 5/7.
